apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
  namespace: bookstore
data:
  tempo.yml: |
    server:
      http_listen_port: 3200
    distributor:
      receivers:
        otlp:
          protocols:
            grpc:
            http:
        zipkin:
    ingester:
      trace_idle_period: 10s
      max_block_bytes: 1_000_000
      max_block_duration: 5m
    compactor:
      compaction:
        compaction_window: 1h
        max_compaction_objects: 1000000
        block_retention: 1h
        compacted_block_retention: 10m
    storage:
      trace:
        backend: local
        local:
          path: /tmp/tempo/blocks
        pool:
          max_workers: 100
          queue_depth: 10000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo
  namespace: bookstore
  labels:
    app: tempo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      containers:
        - name: tempo
          image: grafana/tempo:2.4.1
          args: ["-config.file=/etc/tempo-config.yml"]
          ports:
            - containerPort: 3200
            - containerPort: 9411
          volumeMounts:
            - name: tempo-config
              mountPath: /etc/tempo-config.yml
              subPath: tempo.yml
      volumes:
        - name: tempo-config
          configMap:
            name: tempo-config
---
apiVersion: v1
kind: Service
metadata:
  name: tempo
  namespace: bookstore
spec:
  type: ClusterIP
  selector:
    app: tempo
  ports:
    - name: tempo
      port: 3200
      targetPort: 3200
    - name: zipkin
      port: 9411
      targetPort: 9411
