apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: bookstore
data:
  SPRING_PROFILES_ACTIVE: "docker"
  CATALOG_SERVICE_URL: "http://catalog-service:8081"
  ORDER_SERVICE_URL: "http://order-service:8082"
  MANAGEMENT_TRACING_ENABLED: "true"
  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: "http://tempo:9411"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: bookstore
  labels:
    app: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
        logging: "promtail"
    spec:
      containers:
        - name: api-gateway
          image: sureshkamediya/bookstore-api-gateway
          ports:
            - containerPort: 8989
          envFrom:
            - configMapRef:
                name: api-gateway-config
          resources:
            limits:
              memory: 700Mi
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: bookstore
spec:
  type: ClusterIP
  selector:
    app: api-gateway
  ports:
    - port: 8989
      targetPort: 8989
