apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-service-config
  namespace: bookstore
data:
  SPRING_PROFILES_ACTIVE: "docker"
  DB_URL: "jdbc:postgresql://catalog-db:5432/postgres"
  SWAGGER_API_GATEWAY_URL: "http://api-gateway:8989/catalog"
  MANAGEMENT_TRACING_ENABLED: "true"
  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: "http://tempo:9411"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
  namespace: bookstore
  labels:
    app: catalog-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-service
  template:
    metadata:
      labels:
        app: catalog-service
        logging: "promtail"
    spec:
      containers:
        - name: catalog-service
          image: sureshkamediya/bookstore-catalog-service
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: catalog-service-config
            - secretRef:
                name: postgres-credentials
          env:
            - name: BPL_JVM_THREAD_COUNT
              value: "50"
          resources:
            requests:
              memory: 400Mi
            limits:
              memory: 700Mi
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-service
  namespace: bookstore
spec:
  type: ClusterIP
  selector:
    app: catalog-service
  ports:
    - port: 8081
      targetPort: 8081
